### ISSUE TITLE
What cluster configuration do I need to deploy Aviary?

### ISSUE THREAD

**Issue by amogkam** [ray-project/aviary#2]
How do I know how many GPUs, memory, etc. I need in my Ray cluster to deploy Aviary? Or will it work regardless of what resources I have?

**Comment by Yard1** [comment]
You can view the default configuration in https://github.com/ray-project/aviary/blob/master/deploy/ray/aviary-cluster.yaml

**Comment by amogkam** [comment]
Got it. How about for each model in particular? Like for model X I need this instance type?

**Comment by Yard1** [comment]
The instance types per model are defined using Ray custom resources - see https://github.com/ray-project/aviary/blob/master/models/README.md for more details

**Comment by amogkam** [comment]
got it, thanks!
