### ISSUE TITLE
How can we use hosted version by making an api call?

### ISSUE THREAD

**Issue by sanjay-nit** [ray-project/aviary#22]
It is possible to make requests to hosted version server?

**Comment by Yard1** [comment]
If you mean the version that we are hosting on aviary.anyscale.com, we are not allowing that. You can either deploy aviary yourself, or contact aviary@anyscale.com for more information regarding hosting on Anyscale.

**Comment by sanjay-nit** [comment]
Thanks for your reply @Yard1 .
One more question, Can we deploy aviary LLM models on [banana.dev](https://www.banana.dev/) GPUs. TIA.

**Comment by Yard1** [comment]
I haven't used banana.dev myself but as long as you can run Ray on those (and you should be able to), I don't see why not
