### ISSUE TITLE
Deploy 2 models via `aviary run` - `aviary model list` only displays 1

### ISSUE THREAD

**Issue by brent-anyscale** [ray-project/aviary#30]
If I deploy 2 models with separate `aviary run` commands, `aviary model list` only displays the last one deployed - however in the ray dashboard, it looks like two are running.

Is it possible to deploy two models with separate `aviary run` commands?
If it is, `aviary model list` should display both models

**Comment by Yard1** [comment]
Running `aviary run` multiple times is currently not supported. Do `aviary run --model MODEL --model MODEL`.

This will be fixed in the future

**Comment by AmeerHajAli** [comment]
From Robin: They are not able to query these two models.

**Comment by robin-anyscale** [comment]
@brent-anyscale can you please confirm, are they able to query the two running models?

**Comment by avnishn** [comment]
This is now resolved.
