### ISSUE TITLE
Leaderboard can be manipulated

### ISSUE THREAD

**Issue by HT224** [ray-project/aviary#6]
Users aren't currently limited to one vote on 'best response' per prompt submitted or forced to 'change vote' to select a different option.

Steps to reproduce:
- Submit prompt
- Select Best Answer X times
- Refresh leaderboard

[Loom Video](https://www.loom.com/share/06f1f4b490e24b09b17c3739f58be6b8)

**Comment by waleedkadous** [comment]
Will prioritize fixing this ASAP. Thank you for reporting the bug!

**Comment by Yard1** [comment]
Should be fixed in 8c90d05d30e823e4897ce18460fabfb39296757a
